name: Reusable test

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: "1"
      os:
        required: false
        type: string
        default: ubuntu-latest
      arch:
        required: false
        type: string
        default: x64
      allow_failure:
        required: false
        type: boolean
        default: false
      run_codecov:
        required: false
        type: boolean
        default: false
    secrets:
      codecov_token:
        required: true
env:
  JULIA_NUM_THREADS: auto

jobs:
  test:
    name: Julia ${{ inputs.version }} - ${{ inputs.os }} - ${{ inputs.arch }} - ${{ github.event_name }}
    runs-on: ${{ inputs.os }}
    continue-on-error: ${{ inputs.allow_failure }}

    steps:
      - uses: actions/checkout@v7
      - name: Install go-sendxmpp
        run: sudo apt install go-sendxmpp
      - name: Create data/ dir
        run: mkdir -p scripts/data
      - name: Start prosody server
        run: docker compose -f scripts/docker-compose.yml up -d
      - name: create user pinocchio
        run: docker compose -f scripts/docker-compose.yml exec prosody prosodyctl register pinocchio localhost plopiplop
      - name: create user gepetto
        run: docker compose -f scripts/docker-compose.yml exec prosody prosodyctl register gepetto localhost plopiplop
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ inputs.version }}
          arch: ${{ inputs.arch }}
      - name: Use Julia cache
        uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
        if: ${{ inputs.run_codecov }}
      - uses: codecov/codecov-action@v5
        if: ${{ inputs.run_codecov }}
        with:
          file: lcov.info
          token: ${{ secrets.codecov_token }}
      - name: Stop containers
        if: always()
        run: docker compose -f scripts/docker-compose.yml down
